(function(g){ window.CP && window.CP.setGrade ? window.CP.setGrade(g) : (window.GRADES = window.GRADES || []).push(g); })({
  g:5,
  books:[
    { n:"五年级上册", u:[
      { n:"Unit 1 Classmates 同学", w:[{e:"clever",z:"聪明的",k:"🧠"},{e:"careless",z:"粗心的",k:"🤦"},{e:"polite",z:"有礼貌的",k:"🙇"},{e:"quiet",z:"安静的",k:"🤫"},{e:"cute",z:"可爱的",k:"🥰"},{e:"friendly",z:"友好的",k:"🤝"},{e:"helpful",z:"乐于助人的",k:"💪"},{e:"active",z:"活跃的",k:"🏃"},{e:"popular",z:"受欢迎的",k:"🌟"},{e:"talkative",z:"健谈的",k:"🗣️"},{e:"hardworking",z:"刻苦的",k:"📚"},{e:"honest",z:"诚实的",k:"😇"},{e:"funny",z:"有趣的",k:"😂"},{e:"lazy",z:"懒惰的",k:"🦥"},{e:"talk",z:"说话",k:"💬"},{e:"party",z:"聚会",k:"🎉"},{e:"sometimes",z:"有时",k:"⏳"}], s:[{e:"What is Tom like? He is clever and helpful.",z:"汤姆是个怎样的人？他聪明又乐于助人。"},{e:"He is very popular, but sometimes he is careless.",z:"他很受欢迎，但有时很粗心。"},{e:"What is he good at? He is good at maths.",z:"他擅长什么？他擅长数学。"}] },
      { n:"Unit 2 Teachers 老师", w:[{e:"wear glasses",z:"戴眼镜",k:"👓"},{e:"slim",z:"苗条的",k:"🧍"},{e:"curly",z:"卷曲的",k:"🌀"},{e:"straight",z:"直的",k:"📏"},{e:"nice",z:"好的",k:"👍"},{e:"young",z:"年轻的",k:"🧑"},{e:"teach",z:"教",k:"👩‍🏫"},{e:"guess",z:"猜",k:"🤔"},{e:"kind",z:"和蔼的",k:"😊"},{e:"strict",z:"严格的",k:"😐"},{e:"handsome",z:"英俊的",k:"😎"},{e:"beautiful",z:"美丽的",k:"🌸"},{e:"tall",z:"高的",k:"📐"},{e:"short",z:"矮的",k:"🔻"},{e:"old",z:"年老的",k:"👴"},{e:"long hair",z:"长发",k:"💇"},{e:"short hair",z:"短发",k:"✂️"}], s:[{e:"What does he teach? He teaches maths.",z:"他教什么？他教数学。"},{e:"Who is your favourite teacher? Mrs Young. She has long curly hair.",z:"谁是你最喜欢的老师？杨老师，她有一头长卷发。"},{e:"He wears glasses. He is nice and young.",z:"他戴眼镜，人很好也很年轻。"}] },
      { n:"Unit 3 Animals 动物", w:[{e:"animal",z:"动物",k:"🐾"},{e:"elephant",z:"大象",k:"🐘"},{e:"panda",z:"熊猫",k:"🐼"},{e:"horse",z:"马",k:"🐴"},{e:"cow",z:"奶牛",k:"🐄"},{e:"pig",z:"猪",k:"🐷"},{e:"sheep",z:"绵羊",k:"🐑"},{e:"bee",z:"蜜蜂",k:"🐝"},{e:"farm",z:"农场",k:"🚜"},{e:"fast",z:"快的",k:"🐎"},{e:"butterfly",z:"蝴蝶",k:"🦋"},{e:"tiger",z:"老虎",k:"🐯"},{e:"monkey",z:"猴子",k:"🐵"},{e:"lion",z:"狮子",k:"🦁"},{e:"giraffe",z:"长颈鹿",k:"🦒"},{e:"turtle",z:"乌龟",k:"🐢"},{e:"bamboo",z:"竹子",k:"🎋"},{e:"slow",z:"慢的",k:"🐌"}], s:[{e:"What is your favourite animal? My favourite animal is the panda.",z:"你最喜欢的动物是什么？我最喜欢熊猫。"},{e:"It lives in a bamboo forest and eats bamboo.",z:"它住在竹林里，吃竹子。"},{e:"It has a long nose called a trunk.",z:"它有一个叫象鼻的长鼻子。"}] },
      { n:"Unit 4 Shopping Day 购物日", w:[{e:"exercise book",z:"练习本",k:"📓"},{e:"pencil sharpener",z:"铅笔刀",k:"✏️"},{e:"a pair of scissors",z:"一把剪刀",k:"✂️"},{e:"pencil box",z:"铅笔盒",k:"📦"},{e:"a box of crayons",z:"一盒蜡笔",k:"🖍️"},{e:"please",z:"请",k:"🙏"},{e:"only",z:"仅仅",k:"1️⃣"},{e:"saleswoman",z:"女售货员",k:"👩‍💼"},{e:"notebook",z:"笔记本",k:"📔"},{e:"eraser",z:"橡皮",k:"🧽"},{e:"pen",z:"钢笔",k:"🖊️"},{e:"ruler",z:"尺子",k:"📏"},{e:"dictionary",z:"词典",k:"📕"},{e:"toy car",z:"玩具车",k:"🚗"},{e:"present",z:"礼物",k:"🎁"},{e:"how much",z:"多少钱",k:"💰"}], s:[{e:"Can I help you? Yes. I want a pair of scissors.",z:"需要帮忙吗？是的，我想要一把剪刀。"},{e:"How much is it? It is 10 yuan.",z:"多少钱？10 元。"},{e:"A box of crayons is only 10 yuan.",z:"一盒蜡笔只要 10 元。"}] },
      { n:"Unit 5 TV Shows 电视节目", w:[{e:"wonderful",z:"精彩的",k:"🌟"},{e:"cool",z:"酷的",k:"😎"},{e:"fantastic",z:"极好的",k:"🎉"},{e:"cartoons",z:"动画片",k:"🎬"},{e:"news shows",z:"新闻节目",k:"📰"},{e:"nature shows",z:"自然节目",k:"🌿"},{e:"TV shows",z:"电视节目",k:"📺"},{e:"sports shows",z:"体育节目",k:"⚽"},{e:"music shows",z:"音乐节目",k:"🎵"},{e:"talk shows",z:"谈话节目",k:"🎙️"},{e:"cooking shows",z:"烹饪节目",k:"🍳"},{e:"movie",z:"电影",k:"🎥"},{e:"interesting",z:"有趣的",k:"😄"},{e:"boring",z:"无聊的",k:"😴"},{e:"exciting",z:"令人兴奋的",k:"🎢"},{e:"watch TV",z:"看电视",k:"🛋️"}], s:[{e:"What are your favourite TV shows? My favourite TV shows are sports shows.",z:"你最喜欢什么电视节目？我最喜欢体育节目。"},{e:"When do you usually watch them? I usually watch them on Saturday evening.",z:"你通常什么时候看？我通常周六晚上看。"},{e:"I think nature shows are wonderful.",z:"我觉得自然节目很精彩。"}] },
      { n:"Unit 6 Chores 家务", w:[{e:"chore",z:"家务",k:"🏠"},{e:"clean the room",z:"打扫房间",k:"🧽"},{e:"make the bed",z:"整理床铺",k:"🛏️"},{e:"take out the rubbish",z:"倒垃圾",k:"🗑️"},{e:"wash clothes",z:"洗衣服",k:"🧺"},{e:"tidy the desk",z:"清理书桌",k:"🗄️"},{e:"sweep the floor",z:"扫地",k:"🧹"},{e:"water the plants",z:"给植物浇水",k:"🪴"},{e:"feed the fish",z:"喂鱼",k:"🐠"},{e:"walk the dog",z:"遛狗",k:"🐕"},{e:"do the dishes",z:"洗碗",k:"🍽️"},{e:"set the table",z:"摆餐具",k:"🍴"},{e:"cook breakfast",z:"做早餐",k:"🍳"},{e:"always",z:"总是",k:"🔁"},{e:"usually",z:"通常",k:"🔂"},{e:"often",z:"经常",k:"🕐"},{e:"busy",z:"忙碌的",k:"🐝"}], s:[{e:"What chores do you usually do at home? I usually tidy my desk and clean my room.",z:"你在家通常做什么家务？我通常清理书桌、打扫房间。"},{e:"Do you help your parents do chores at home? Yes, I do.",z:"你在家帮父母做家务吗？是的。"},{e:"I am going to wash clothes and sweep the floor.",z:"我打算洗衣服和扫地。"}] }
    ]},
    { n:"五年级下册", u:[
      { n:"Unit 1 Keeping Healthy 保持健康", w:[{e:"too much",z:"太多",k:"🚫"},{e:"candy",z:"糖果",k:"🍬"},{e:"go to bed",z:"上床睡觉",k:"🛏️"},{e:"early",z:"早的",k:"🌅"},{e:"exercise",z:"锻炼",k:"🏃"},{e:"tired",z:"疲倦的",k:"😪"},{e:"drink",z:"喝",k:"🥤"},{e:"before",z:"在…之前",k:"⏪"},{e:"dirty",z:"脏的",k:"🗑️"},{e:"stomachache",z:"胃疼",k:"🤢"},{e:"headache",z:"头疼",k:"🤕"},{e:"toothache",z:"牙疼",k:"🦷"},{e:"sleepy",z:"困的",k:"😴"},{e:"advice",z:"建议",k:"💡"},{e:"wash hands",z:"洗手",k:"🧼"},{e:"healthy",z:"健康的",k:"🥗"}], s:[{e:"What is wrong? I have got a stomachache.",z:"怎么了？我肚子疼。"},{e:"What should I do? You should drink some water.",z:"我该怎么办？你应该喝点水。"},{e:"You should not eat too much candy.",z:"你不该吃太多糖果。"}] },
      { n:"Unit 2 Special Days 特殊的日子", w:[{e:"New Year's Day",z:"新年",k:"🎆"},{e:"Tree Planting Day",z:"植树节",k:"🌱"},{e:"Mother's Day",z:"母亲节",k:"💐"},{e:"Children's Day",z:"儿童节",k:"🎈"},{e:"Father's Day",z:"父亲节",k:"👔"},{e:"Teachers' Day",z:"教师节",k:"🍎"},{e:"National Day",z:"国庆节",k:"🇨🇳"},{e:"Christmas Day",z:"圣诞节",k:"🎄"},{e:"birthday",z:"生日",k:"🎂"},{e:"fifth",z:"第五",k:"5️⃣"},{e:"tenth",z:"第十",k:"🔟"},{e:"twelfth",z:"第十二",k:"1️⃣2️⃣"},{e:"plant",z:"种植",k:"🌿"},{e:"celebrate",z:"庆祝",k:"🥳"},{e:"have a picnic",z:"去野餐",k:"🧺"},{e:"together",z:"一起",k:"👫"},{e:"special",z:"特别的",k:"✨"}], s:[{e:"When is Tree Planting Day? It is on March 12th.",z:"植树节是什么时候？3 月 12 日。"},{e:"What do you do on that day? We often plant trees.",z:"那天你们做什么？我们经常植树。"},{e:"How are you going to celebrate it? We are going to have a picnic.",z:"你们打算怎么庆祝？我们打算去野餐。"}] },
      { n:"Unit 3 Making Contact 取得联系", w:[{e:"send an email",z:"发电子邮件",k:"📧"},{e:"write a letter",z:"写信",k:"✍️"},{e:"make a phone call",z:"打电话",k:"☎️"},{e:"send a short message",z:"发短信",k:"📱"},{e:"mail a present",z:"邮寄礼物",k:"📮"},{e:"make a video call",z:"打视频电话",k:"📹"},{e:"make a card",z:"制作卡片",k:"💌"},{e:"everywhere",z:"到处",k:"🌍"},{e:"flower show",z:"花展",k:"🌷"},{e:"contact",z:"联系",k:"🔗"},{e:"letter",z:"信",k:"✉️"},{e:"postcard",z:"明信片",k:"🏞️"},{e:"invite",z:"邀请",k:"🤝"},{e:"tomorrow",z:"明天",k:"📅"},{e:"photo",z:"照片",k:"📸"},{e:"gift",z:"礼物",k:"🎁"}], s:[{e:"What do you want to do on New Year's Day? I want to write a letter to my father.",z:"新年你想做什么？我想给爸爸写封信。"},{e:"What would you like to do? I would like to say I love you to my mother.",z:"你想做什么？我想对妈妈表达爱意。"},{e:"You can make a card for your mother.",z:"你可以给妈妈做张卡片。"}] },
      { n:"Unit 4 Last Weekend 上周末", w:[{e:"cleaned the window",z:"擦窗户",k:"🪟"},{e:"watched TV",z:"看电视",k:"📺"},{e:"climbed a hill",z:"爬山",k:"⛰️"},{e:"visited grandparents",z:"看望祖父母",k:"👵"},{e:"danced",z:"跳舞",k:"💃"},{e:"jumped rope",z:"跳绳",k:"🪢"},{e:"listened to music",z:"听音乐",k:"🎧"},{e:"rowed a boat",z:"划船",k:"🚣"},{e:"played computer games",z:"玩电脑游戏",k:"🎮"},{e:"stayed at home",z:"待在家",k:"🏠"},{e:"played the piano",z:"弹钢琴",k:"🎹"},{e:"played chess",z:"下棋",k:"♟️"},{e:"washed clothes",z:"洗衣服",k:"🧺"},{e:"badminton",z:"羽毛球",k:"🏸"},{e:"won",z:"赢",k:"🏆"},{e:"weekend",z:"周末",k:"🗓️"},{e:"ill",z:"生病的",k:"🤒"}], s:[{e:"What did you do last weekend? I visited my grandparents.",z:"上周末你做什么了？我去看望祖父母了。"},{e:"How was your weekend? It was wonderful.",z:"周末过得怎么样？很棒。"},{e:"I played the piano and washed clothes.",z:"我弹了钢琴，还洗了衣服。"}] },
      { n:"Unit 5 Have a Great Trip 旅途愉快", w:[{e:"went to the beach",z:"去海边",k:"🏖️"},{e:"drank cold drinks",z:"喝冷饮",k:"🥤"},{e:"swam",z:"游泳",k:"🏊"},{e:"ate ice cream",z:"吃冰淇淋",k:"🍦"},{e:"bought some gifts",z:"买礼物",k:"🛍️"},{e:"took photos",z:"拍照",k:"📸"},{e:"saw flowers",z:"赏花",k:"🌸"},{e:"slept",z:"睡觉",k:"😴"},{e:"delicious",z:"美味的",k:"😋"},{e:"felt happy",z:"感到高兴",k:"😊"},{e:"sad",z:"难过的",k:"😢"},{e:"left",z:"离开",k:"👋"},{e:"French fries",z:"薯条",k:"🍟"},{e:"trip",z:"旅行",k:"✈️"},{e:"beach",z:"海滩",k:"🏝️"},{e:"vacation",z:"假期",k:"🌴"}], s:[{e:"How was your summer vacation? It was fun.",z:"暑假过得怎么样？很有趣。"},{e:"Where did you go? I went to Beijing with my parents.",z:"你去哪儿了？我和父母去了北京。"},{e:"What did you do there? We took photos and ate Beijing duck.",z:"你们在那儿做了什么？我们拍照、吃了北京烤鸭。"}] },
      { n:"Unit 6 Growing Up 成长", w:[{e:"was born",z:"出生",k:"👶"},{e:"started to speak",z:"开始说话",k:"🗣️"},{e:"learned to walk",z:"学走路",k:"🚶"},{e:"learned to ride a bike",z:"学骑自行车",k:"🚲"},{e:"went to kindergarten",z:"上幼儿园",k:"🧸"},{e:"went to school",z:"上学",k:"🎒"},{e:"learned to swim",z:"学游泳",k:"🏊"},{e:"fifteenth",z:"第十五",k:"1️⃣5️⃣"},{e:"started to buy things",z:"开始买东西",k:"🛒"},{e:"started to study English",z:"开始学英语",k:"🔤"},{e:"started to use a computer",z:"开始用电脑",k:"💻"},{e:"chopsticks",z:"筷子",k:"🥢"},{e:"wet",z:"湿的",k:"💧"},{e:"grow up",z:"长大",k:"🌱"},{e:"baby",z:"婴儿",k:"🍼"},{e:"month",z:"月",k:"📆"},{e:"start",z:"开始",k:"▶️"}], s:[{e:"When were you born? I was born on May 15th, 2004.",z:"你什么时候出生的？我出生于 2004 年 5 月 15 日。"},{e:"When did you start to use a computer? When I was four.",z:"你什么时候开始用电脑的？我四岁时。"},{e:"I started to speak when I was ten months old.",z:"我十个月大时开始说话。"}] }
    ]}
  ]
});
