(function(g){ window.CP && window.CP.setGrade ? window.CP.setGrade(g) : (window.GRADES = window.GRADES || []).push(g); })({
  g:3,
  books:[
    { n:"三年级上册", u:[
      { n:"Unit 1 Myself 我自己", w:[{e:"name",z:"名字",k:"✏️"},{e:"new",z:"新的",k:"🆕"},{e:"year",z:"年",k:"📅"},{e:"old",z:"…岁的",k:"🔢"},{e:"class",z:"班",k:"👥"},{e:"grade",z:"年级",k:"🎓"},{e:"age",z:"年龄",k:"⏳"},{e:"school",z:"学校",k:"🏫"},{e:"teacher",z:"老师",k:"👩‍🏫"}], s:[{e:"What's your name?",z:"你叫什么名字？"},{e:"How old are you?",z:"你几岁了？"}] },
      { n:"Unit 2 My Body 身体", w:[{e:"body",z:"身体",k:"🧍"},{e:"head",z:"头",k:"👤"},{e:"hair",z:"头发",k:"💇"},{e:"arm",z:"胳膊",k:"💪"},{e:"hand",z:"手",k:"✋"},{e:"leg",z:"腿",k:"🦵"},{e:"foot",z:"脚",k:"👣"},{e:"face",z:"脸",k:"😊"},{e:"eye",z:"眼睛",k:"👁️"},{e:"nose",z:"鼻子",k:"👃"},{e:"mouth",z:"嘴",k:"👄"},{e:"ear",z:"耳朵",k:"👂"}], s:[{e:"I have two eyes and a small head.",z:"我有两只眼睛和一个小脑袋。"},{e:"What's the matter?",z:"怎么了？"}] },
      { n:"Unit 3 Food 食物", w:[{e:"bread",z:"面包",k:"🍞"},{e:"cake",z:"蛋糕",k:"🍰"},{e:"fruit",z:"水果",k:"🍎"},{e:"ice cream",z:"冰淇淋",k:"🍦"},{e:"potato",z:"土豆",k:"🥔"},{e:"tomato",z:"西红柿",k:"🍅"},{e:"meat",z:"肉",k:"🥩"},{e:"rice",z:"米饭",k:"🍚"},{e:"noodles",z:"面条",k:"🍜"},{e:"vegetables",z:"蔬菜",k:"🥦"},{e:"fish",z:"鱼",k:"🐟"},{e:"chicken",z:"鸡肉",k:"🍗"},{e:"egg",z:"蛋",k:"🥚"},{e:"cola",z:"可乐",k:"🥤"}], s:[{e:"What do you want for breakfast?",z:"你早餐想吃什么？"},{e:"Do you like ice cream?",z:"你喜欢冰淇淋吗？"}] },
      { n:"Unit 4 Pets 宠物", w:[{e:"duck",z:"鸭子",k:"🦆"},{e:"chicken",z:"鸡",k:"🐔"},{e:"rabbit",z:"兔子",k:"🐰"},{e:"pet",z:"宠物",k:"🐾"},{e:"snake",z:"蛇",k:"🐍"},{e:"turtle",z:"乌龟",k:"🐢"},{e:"cat",z:"猫",k:"🐱"},{e:"dog",z:"狗",k:"🐶"},{e:"bird",z:"鸟",k:"🐦"},{e:"monkey",z:"猴子",k:"🐵"},{e:"tiger",z:"老虎",k:"🐯"},{e:"fish",z:"鱼",k:"🐠"},{e:"tail",z:"尾巴",k:"🐈"}], s:[{e:"What pet do you have?",z:"你养什么宠物？"},{e:"It has a long tail.",z:"它有一条长尾巴。"}] },
      { n:"Unit 5 Clothes 衣服", w:[{e:"cap",z:"帽子",k:"🧢"},{e:"coat",z:"大衣",k:"🧥"},{e:"shoes",z:"鞋",k:"👟"},{e:"sweater",z:"毛衣",k:"🧶"},{e:"jacket",z:"夹克",k:"🥼"},{e:"gloves",z:"手套",k:"🧤"},{e:"trousers",z:"裤子",k:"👖"},{e:"T-shirt",z:"T恤",k:"👕"},{e:"shorts",z:"短裤",k:"🩳"},{e:"socks",z:"短袜",k:"🧦"},{e:"skirt",z:"裙子",k:"🥻"},{e:"dress",z:"连衣裙",k:"👗"},{e:"shirt",z:"衬衫",k:"👔"}], s:[{e:"Do you have a cap?",z:"你有帽子吗？"},{e:"What colour is your dress?",z:"你的连衣裙是什么颜色的？"}] },
      { n:"Unit 6 Birthdays 生日", w:[{e:"January",z:"一月",k:"🎍"},{e:"February",z:"二月",k:"💝"},{e:"March",z:"三月",k:"🍀"},{e:"April",z:"四月",k:"🌸"},{e:"May",z:"五月",k:"🌺"},{e:"June",z:"六月",k:"🍉"},{e:"July",z:"七月",k:"☀️"},{e:"August",z:"八月",k:"🏖️"},{e:"September",z:"九月",k:"🍎"},{e:"October",z:"十月",k:"🎃"},{e:"November",z:"十一月",k:"🍂"},{e:"December",z:"十二月",k:"❄️"},{e:"birthday",z:"生日",k:"🎂"},{e:"party",z:"聚会",k:"🎉"}], s:[{e:"When is your birthday?",z:"你的生日是什么时候？"},{e:"My birthday is in May.",z:"我的生日在五月。"}] }
    ]},
    { n:"三年级下册", u:[
      { n:"Unit 1 School Subjects 学校课程", w:[{e:"Chinese",z:"语文",k:"🇨🇳"},{e:"English",z:"英语",k:"🇬🇧"},{e:"science",z:"科学",k:"🔬"},{e:"PE",z:"体育",k:"🏃"},{e:"music",z:"音乐",k:"🎵"},{e:"maths",z:"数学",k:"➗"},{e:"art",z:"美术",k:"🎨"},{e:"computer class",z:"计算机课",k:"💻"},{e:"subject",z:"科目",k:"📚"},{e:"favourite",z:"最喜欢的",k:"⭐"}], s:[{e:"What's your favourite subject?",z:"你最喜欢的科目是什么？"},{e:"My favourite subject is English.",z:"我最喜欢英语。"}] },
      { n:"Unit 2 My School 学校", w:[{e:"classroom",z:"教室",k:"🏫"},{e:"library",z:"图书馆",k:"📚"},{e:"toilet",z:"厕所",k:"🚻"},{e:"playground",z:"操场",k:"🛝"},{e:"first",z:"第一",k:"🥇"},{e:"second",z:"第二",k:"🥈"},{e:"third",z:"第三",k:"🥉"},{e:"floor",z:"层",k:"🏢"},{e:"room",z:"房间",k:"🏠"},{e:"gym",z:"体育馆",k:"🤸"}], s:[{e:"Where is the library?",z:"图书馆在哪里？"},{e:"It's on the first floor.",z:"它在一楼。"}] },
      { n:"Unit 3 After School 放学后", w:[{e:"after school",z:"放学后",k:"🕒"},{e:"do sports",z:"做运动",k:"🏃"},{e:"draw pictures",z:"画画",k:"🎨"},{e:"play chess",z:"下棋",k:"♟️"},{e:"dance",z:"跳舞",k:"💃"},{e:"sing songs",z:"唱歌",k:"🎤"},{e:"read books",z:"读书",k:"📖"},{e:"play football",z:"踢足球",k:"⚽"},{e:"fly a kite",z:"放风筝",k:"🪁"},{e:"ride a bike",z:"骑自行车",k:"🚲"},{e:"swim",z:"游泳",k:"🏊"},{e:"make a snowman",z:"堆雪人",k:"⛄"}], s:[{e:"What are you going to do after school?",z:"放学后你打算做什么？"},{e:"I'm going to play football.",z:"我打算去踢足球。"}] },
      { n:"Unit 4 My Family 家庭", w:[{e:"family",z:"家庭",k:"👨‍👩‍👧"},{e:"father",z:"父亲",k:"👨"},{e:"mother",z:"母亲",k:"👩"},{e:"grandfather",z:"祖父",k:"👴"},{e:"grandmother",z:"祖母",k:"👵"},{e:"brother",z:"兄弟",k:"👦"},{e:"sister",z:"姐妹",k:"👧"},{e:"uncle",z:"叔叔",k:"🧔"},{e:"aunt",z:"阿姨",k:"👱‍♀️"},{e:"cousin",z:"堂表亲",k:"🧒"},{e:"handsome",z:"英俊的",k:"😎"},{e:"beautiful",z:"美丽的",k:"🌹"}], s:[{e:"Is she your aunt?",z:"她是你的姑姑吗？"},{e:"Who's that man?",z:"那个男人是谁？"}] },
      { n:"Unit 5 Family Activities 家庭活动", w:[{e:"watching TV",z:"看电视",k:"📺"},{e:"cooking dinner",z:"做饭",k:"🍳"},{e:"cleaning the room",z:"打扫房间",k:"🧹"},{e:"listening to music",z:"听音乐",k:"🎧"},{e:"walking the dog",z:"遛狗",k:"🐕"},{e:"feeding the fish",z:"喂鱼",k:"🐟"},{e:"watering the plants",z:"给植物浇水",k:"💦"},{e:"read stories",z:"读故事",k:"📚"},{e:"watch movies",z:"看电影",k:"🎬"},{e:"have a picnic",z:"野餐",k:"🧺"}], s:[{e:"What are you doing?",z:"你在做什么？"},{e:"I'm watching TV.",z:"我在看电视。"}] },
      { n:"Unit 6 My Home 家", w:[{e:"home",z:"家",k:"🏠"},{e:"bedroom",z:"卧室",k:"🛌"},{e:"living room",z:"客厅",k:"📺"},{e:"dining room",z:"餐厅",k:"🍽️"},{e:"kitchen",z:"厨房",k:"🍳"},{e:"bathroom",z:"浴室",k:"🛁"},{e:"study",z:"书房",k:"📚"},{e:"sofa",z:"沙发",k:"🛋️"},{e:"bed",z:"床",k:"🛏️"},{e:"door",z:"门",k:"🚪"},{e:"light",z:"灯",k:"💡"},{e:"box",z:"盒子",k:"📦"}], s:[{e:"Where is my aunt?",z:"我姑姑在哪里？"},{e:"She's in the kitchen.",z:"她在厨房里。"}] }
    ]}
  ]
});
